/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function typstrendererbuilder_new(a: number): void;
export function typstrendererbuilder_build(a: number): number;
export function __wbg_rendersessionoptions_free(a: number, b: number): void;
export function rendersessionoptions_new(): number;
export function rendersessionoptions_pixel_per_pt(a: number, b: number): void;
export function rendersessionoptions_set_pixel_per_pt(a: number, b: number): void;
export function rendersessionoptions_background_color(a: number, b: number): void;
export function rendersessionoptions_set_background_color(a: number, b: number, c: number): void;
export function rendersessionoptions_format(a: number, b: number): void;
export function rendersessionoptions_set_format(a: number, b: number, c: number): void;
export function __wbg_createsessionoptions_free(a: number, b: number): void;
export function createsessionoptions_new(): number;
export function createsessionoptions_set_format(a: number, b: number, c: number): void;
export function createsessionoptions_set_artifact_content(a: number, b: number, c: number): void;
export function __wbg_pageinfo_free(a: number, b: number): void;
export function pageinfo_page_off(a: number): number;
export function pageinfo_width_pt(a: number): number;
export function pageinfo_height_pt(a: number): number;
export function __wbg_pagesinfo_free(a: number, b: number): void;
export function pagesinfo_page_count(a: number): number;
export function pagesinfo_page_by_number(a: number, b: number): number;
export function pagesinfo_page(a: number, b: number): number;
export function pagesinfo_width(a: number): number;
export function pagesinfo_height(a: number): number;
export function __wbg_rendersession_free(a: number, b: number): void;
export function rendersession_pixel_per_pt(a: number, b: number): void;
export function rendersession_set_pixel_per_pt(a: number, b: number): void;
export function rendersession_background_color(a: number, b: number): void;
export function rendersession_set_background_color(a: number, b: number, c: number): void;
export function rendersession_pages_info(a: number): number;
export function rendersession_doc_width(a: number): number;
export function rendersession_doc_height(a: number): number;
export function rendersession_source_span(a: number, b: number, c: number, d: number): void;
export function qcms_transform_data_rgb_out_lut_precache(a: number, b: number, c: number, d: number): void;
export function qcms_transform_data_rgba_out_lut_precache(a: number, b: number, c: number, d: number): void;
export function qcms_transform_data_bgra_out_lut_precache(a: number, b: number, c: number, d: number): void;
export function qcms_transform_data_rgb_out_lut(a: number, b: number, c: number, d: number): void;
export function qcms_transform_data_rgba_out_lut(a: number, b: number, c: number, d: number): void;
export function qcms_transform_data_bgra_out_lut(a: number, b: number, c: number, d: number): void;
export function qcms_transform_release(a: number): void;
export function qcms_profile_precache_output_transform(a: number): void;
export function qcms_enable_iccv4(): void;
export function qcms_profile_is_bogus(a: number): number;
export function qcms_white_point_sRGB(a: number): void;
export function lut_interp_linear16(a: number, b: number, c: number): number;
export function lut_inverse_interp16(a: number, b: number, c: number): number;
export function __wbg_incrdomdocclient_free(a: number, b: number): void;
export function incrdomdocclient_bind_functions(a: number, b: number): void;
export function incrdomdocclient_relayout(a: number, b: number, c: number, d: number, e: number): number;
export function incrdomdocclient_need_repaint(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): void;
export function incrdomdocclient_repaint(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): void;
export function typstrendererbuilder_add_glyph_pack(a: number, b: number): number;
export function typstrenderer_load_glyph_pack(a: number, b: number, c: number): void;
export function typstrendererbuilder_add_raw_font(a: number, b: number): number;
export function typstrendererbuilder_add_web_fonts(a: number, b: number): number;
export function rendersession_render_in_window(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function typstrenderer_render_svg_diff(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function typstrenderer_svg_data(a: number, b: number, c: number, d: number, e: number): void;
export function typstrenderer_get_customs(a: number, b: number): number;
export function typstrenderer_render_svg(a: number, b: number, c: number, d: number): void;
export function typstrenderer_create_worker(a: number, b: number): number;
export function typstrenderer_create_worker_bridge(a: number, b: number): void;
export function typstworker_manipulate_data(a: number, b: number, c: number, d: number, e: number): void;
export function typstworker_get_pages_info(a: number): number;
export function typstworker_render_canvas(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): void;
export function typstrenderer_mount_dom(a: number, b: number, c: number): number;
export function typstrenderer_render_page_to_canvas(a: number, b: number, c: number, d: number): number;
export function renderer_build_info(): number;
export function __wbg_renderpageimageoptions_free(a: number, b: number): void;
export function renderpageimageoptions_new(): number;
export function renderpageimageoptions_pixel_per_pt(a: number, b: number): void;
export function renderpageimageoptions_set_pixel_per_pt(a: number, b: number, c: number): void;
export function renderpageimageoptions_background_color(a: number, b: number): void;
export function renderpageimageoptions_set_background_color(a: number, b: number, c: number): void;
export function renderpageimageoptions_page_off(a: number): number;
export function renderpageimageoptions_set_page_off(a: number, b: number): void;
export function renderpageimageoptions_cache_key(a: number, b: number): void;
export function renderpageimageoptions_set_cache_key(a: number, b: number, c: number): void;
export function renderpageimageoptions_data_selection(a: number, b: number): void;
export function renderpageimageoptions_set_data_selection(a: number, b: number, c: number): void;
export function __wbg_typstrenderer_free(a: number, b: number): void;
export function typstrenderer_new(): number;
export function typstrenderer_create_session(a: number, b: number, c: number): void;
export function typstrenderer_reset(a: number, b: number, c: number): void;
export function typstrenderer_manipulate_data(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function typstrenderer_session_from_artifact(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function __wbg_workerbridge_free(a: number, b: number): void;
export function __wbg_typstworker_free(a: number, b: number): void;
export function __wbg_typstrendererbuilder_free(a: number, b: number): void;
export function __wbindgen_export_0(a: number, b: number): number;
export function __wbindgen_export_1(a: number, b: number, c: number, d: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function __wbindgen_export_3(a: number, b: number): void;
export function __wbindgen_export_4(a: number, b: number, c: number): void;
export function __wbindgen_export_5(a: number, b: number, c: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_export_6(a: number, b: number, c: number): void;
export function __wbindgen_export_7(a: number): void;
export function __wbindgen_export_8(a: number, b: number, c: number, d: number): void;
